ALTER TABLE CampaignLogs
ADD COLUMN Ip VARCHAR(45),
ADD COLUMN Latitude VARCHAR(50),
ADD COLUMN Longitude VARCHAR(50),
ADD COLUMN City VARCHAR(100),
ADD COLUMN Region VARCHAR(100),
ADD COLUMN Country VARCHAR(100),
ADD COLUMN Browser VARCHAR(100),
ADD COLUMN OS VARCHAR(100);